[package]
name = "tauri-zero"
version = "0.4.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# 更多键与定义见：https://doc.rust-lang.org/cargo/reference/manifest.html
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# `_lib` 后缀看似冗余，但能让库名唯一且不与 bin 名称冲突；这似乎仅是 Windows 问题。
# The `_lib` suffix may seem redundant but it is necessary to make the lib name unique and avoid conflicting with the bin name; this seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_zero_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
dotenvy = "0.15"

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-opener = "2"
tauri-plugin-http = "2"
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
tauri-plugin-notification = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
log = "0.4"
thiserror = "2"
tokio = { version = "1", features = ["sync", "macros", "rt"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite", "derive", "migrate"] }
tauri-plugin-os = "2.3.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61", features = ["Win32_Foundation", "Win32_Graphics_Dwm", "Win32_UI_Controls"] }
